environment:
  matrix:
    - RUBY_VERSION: "25-x64"

cache:
  - vendor/bundle

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

build_script:
  - git submodule update --init --recursive
  - bundle exec ruby ext/xlearn/extconf.rb

test_script:
  - bundle exec rake
